<h2>TICKETS SECTION</h2>
<?php 

$collection = $block->getData('collection');
//echo $customParameter;
//echo $collection->getSelect()->__toString();
//print_r($collection);
?>
<table style="width:100%">
  <tr>
    <th><a href="https://enrico.reflexmania.it/customdb/page/insertform/">INSERT</a></th>
    
  </tr>
  <tr>
    <th><a href="https://enrico.reflexmania.it/customdb/page/updateform/">UPDATE</a></th>
    
  </tr>
  <tr>
    <th><a href="https://enrico.reflexmania.it/customdb/page/deleteform/">DELETE</a></th>
    
  </tr>
</table>