
<div class="wrap">
  
  <h4>Slider with 2 perView, focusAt center</h4>
  
   <div class="glide multi">
    <div class="glide__track" data-glide-el="track">
      <ul class="glide__slides">
        <li class="glide__slide">1</li>
        <li class="glide__slide">2</li>
        <li class="glide__slide">3</li>
      </ul>
    </div>
  </div>
</div>

<script>
requirejs(['jquery','bootstrap',"glide","domReady!"],  function ($, Glide) {
    

  var glideMulti = new Glide('.multi', {
  type: 'slider',
  autoplay: 4000,
  focusAt: 'center',
  perView: 2
});

glideMulti.mount();
});
</script>
