<header>
<div id="messTop">Spedizione Gratuita per ordini superiori a 49.90€. Telefono/WhatsApp: 
<a href="https://wa.me/39350.93.90.090">350.93.90.090</a></div>
</header>

<style>
 #messTop {
padding: 5px 10px;
text-align: center;
background: #1c78ba;
color: #FFF;
font-size: 20px;
font-family: Roboto, Arial, sans-serif;
}

#messTop a {
background: #fff;
color: #2e3192;
padding: 2px 5px;
font-weight: bold;
border-radius: 10px;
font-size: 16px;
}

#messTop a:hover {
    background: yellow;
}

.sidebar .block:not(.account-nav) .block-title, .sidebar .block:not(.account-nav) .title
{
background: #1c78ba !important;
}

.banner-style06 .cdz-banner .cdz-banner-desc{
background-color: #1c78ba !important;
}

.slide-caption .slide-btn a,
.qs-button, a.qs-button
{
border-color: #1c78ba !important;
    background: #1c78ba !important;
color: #fff !important;
}

.qs-button, a.qs-button:hover
{
color: #1c78ba !important;
    border-color: #1c78ba !important;
}

@media only screen and (min-width: 768px)
{
.product-list-style-02 .action.primary
{
border-color: #1c78ba !important;
    background: #1c78ba !important;
}
}

.product-info-main .product-reviews-summary .reviews-actions .action.add,
.post-list-style02 .post-title .post-item-link:hover,
.product-list-style-02 .actions-secondary>.action
{
color: #1c78ba !important;
}

.owl-carousel .owl-nav [class*='owl-']
{
border-color: #1c78ba !important;
    background: #1c78ba !important;
}

.minicart-items .action,
.product-list-style-02 .product-item-actions
{
 background: #1c78ba !important;
    border: 2px solid #1c78ba !important;
}

.cdz-slideshow .owl-dots .owl-dot
{
background-color: #FFF !important;
border: solid 1px #1c78ba;
}

.cdz-slideshow .owl-dots .owl-dot.active
{
background-color: #1c78ba !important;
}

body {
font-family: Roboto, Arial, sans-serif;
}

div#checkout span {
    color: #000;
    font-size: 15px;
    font-weight: 600;
}

.cdz-opc-wrapper .opc-place-order-block .actions-toolbar .primary, .cdz-opc-wrapper .opc-place-order-block .actions-toolbar .action.primary.checkout span {
    color: #fff !important;
}

.cdz-opc-wrapper .opc-place-order-block .actions-toolbar .primary, .cdz-opc-wrapper .opc-place-order-block .actions-toolbar .action.primary.checkout span:hover
{
color: #000 !important;
}

div#mb-bottom-toolbar {
    background: #1c78ba !important;
background-color: #1c78ba !important;
}

.toolbar .pages .action.next:hover, .toolbar .pages .action.previous:hover, .toolbar .pages a.page:hover, .toolbar .pages strong.page
{
background: #1c78ba !important;
background-color: #1c78ba !important;
}

/* Header MOBILE*/
@media only screen and (max-width: 767px)
{
	.product-info-main .product-info-stock-sku .attribute.sku,
	.product-info-main .product-info-stock-sku .stock	
	{
		float: none !important;
	}
		
	.page-header .nav-toggle:before,
	.page-header .nav-toggle>span:before, .page-header .nav-toggle>span:after {
		background: #1c78ba !important;
	}
	.header-search .search-toggle:before,
	.page-header .mobi-cart-wrapper .action.showcart:before
	{
		color: #1c78ba !important;
	}

	.page-header .mobi-cart-wrapper .action.showcart .counter.qty
	{
		color: red !important;
	}
	
	button.action.tocart.primary {
		color: #fff !important;
	}

}

.cdz-opc-wrapper .opc-wrapper .step-title
{
	background: #1c78ba !important;
}

.cdz-opc-wrapper .opc-summary-wrapper
{
	border-color: #1c78ba !important;
}

/* pulsante aggiungi al carrello pagina prodotto */
.account .form-address-edit .actions-toolbar .action.primary, a.action.primary, .action.primary, .cdz-popup-area .cdz-popup .actions-toolbar .primary button,
.product-info-main .box-tocart .primary.tocart,
.modal-popup .modal-inner-wrap .modal-header .action-close
{
	background: #1c78ba !important;
	background-color: #1c78ba !important;
}

.block-minicart .block-title
{
	color: #1c78ba !important;
}

.product.info.detailed .product.items .item.title>.switch:after
{
	background: #1c78ba !important;
}

.double-bounce-spinner .double-bounce1, .double-bounce-spinner .double-bounce2,
.brand-loader.double-bounce-spinner .double-bounce1, .brand-loader.double-bounce-spinner .double-bounce2 {
    background-color: #1c78ba !important;
}

.toolbar .modes-mode
{
	border-color: #1c78ba !important;
}

.toolbar .modes-mode:before 
{
	color: #1c78ba !important;
}

.toolbar .modes-mode:not(.active):hover, .toolbar .modes-mode.active {
    color: #FFF !important;
    border-color: #1c78ba !important;
    background: #1c78ba !important;
}

.toolbar .modes-mode.active:before 
{
	color: #FFF !important;
}

@media only screen and (min-width: 768px){
.product-list-style-03 .wrap-right .product-item-actions {
    
    background: #1c78ba !important;
    border: 2px solid #1c78ba !important;
}
}

#back-top a,
#product-review-container .new-review,
.panel-toggle-wrap.applied .content-toggle
{
	color: #1c78ba !important;
    border-color: #1c78ba !important;
}

#back-top a:hover
.review-add .review-form-actions .submit.primary
{
	border-color: #1c78ba !important;
}

.box-rassicurazione
{
	display: block;
    border-bottom: solid 1px green;
    padding: 10px;
    background: #ceefce;
    color: green;
    margin-bottom: 1px;
	text-align: left;
	text-transform:uppercase;
	font-size: 18px;
}

.box-rassicurazione i
{
	display: inline-block;
	margin-right: 10px;
}

.box-index
{
border: solid 1px #aaa;
    padding: 10px;
}

.panel-toggle-wrap.applied .content-toggle:hover
{
color: #FFFFFF !important;
background: #1c78ba !important;
}
   
</style>